version: 2.1

credentials: &credentials
  - AWS Credentials
  - Airtable Credentials

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          bucket: 's3://cdc-eoc/'
          distribution: 'E1M82XI9UK5PMB'
          context: *credentials
          filters:
            branches:
              only:
                - master

      - deploy:
          bucket: 's3://cdc-eoc-dev/'
          distribution: 'E122Z7UCYXWTES'
          context: *credentials
          filters:
            branches:
              only:
                - dev

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  deploy:
    working_directory: ~/repo

    docker:
      - image: cimg/node:lts

    parameters:
      bucket:
        type: string
      distribution:
        type: string

    steps:
      - checkout
      - aws-cli/install

      - run:
          name: Install packages
          command: npm i

      - run:
          name: Build Site
          command: npm run build

      - run:
          name: Sync to Bucket
          command: aws s3 sync public/ <<parameters.bucket>> --delete

      - run:
          name: Run CloudFront Invalidation
          command: |
            aws cloudfront create-invalidation \
            --distribution-id <<parameters.distribution>> \
            --paths \
            "/*"
