const trainerBios = [
  {
    name: 'Amadou Traoré ',
    photo: 'Traore.jpg',
    bio:
      '<p>Born in Guinea in 1974, Amadou Traore is a French-English bilingual Public Health Emergency Management (PHEM) Officer who graduated medical school in Guinea and worked as a clinician at the Hematology Oncology Unit of the Donka Teaching University before undertaking a short internship at WHO in Geneva. Following this he went onto study English before securing a double Master’s Degree in Biomedical Sciences and Public Health Studies in the UK. He worked at the University College of London and the Institute of Biomedical Research (Edgebaston Hospital) in Birmingham. He is recipient of the US Centers for Disease Control and Prevention (US CDC) PHEM fellowship with several certificates including in emergency management and Field Epidemiology, and as a regional trainer (WHO; West African Health Organisation; US CDC). He has been involved in Public Health Emergency Programme Management; IHR (2005) core capacity building under GHSA (Emergency Preparedness; Emergency Response Operations; Linking Public Health and Security Authorities; Medical Countermeasures & Personnel Deployment and Risk Communications) and Outbreak Investigations in Guinea as a Deputy EOC manager and =Chief of Operations. He assumed coordination roles in public health risk assessments (VRAM, STAR and THIRA) and also tabletop, drill and full-scale simulation exercises both at national and regional levels.</p>',
  },
  {
    name: 'Claire Standley',
    photo: 'Standley.jpg',
    bio:
      '<p>Claire Standley is an Associate Research Professor with the Georgetown Center for Global Health Science and Security. She also maintains an affiliation with the Heidelberg Institute of Global Health in Germany. Her research focuses on the analysis of health systems strengthening and international capacity building for infectious disease prevention and control. Recent projects have included development and implementation of a foundational public health emergency management training curriculum to sub-national responders in Guinea during the Ebola response; laboratory assessments and capacity strengthening in Morocco and Libya; and support to the government of Iraq in implementation of the International Health Regulations (2005). </p><p>Prior to joining Georgetown University, Dr. Standley was a Senior Research Scientist at The George Washington University, and also served as a AAAS Science & Technology Policy Fellow at the US Department of State, where she worked on international biosecurity issues across Africa, western Asia, and the Lower Mekong region. Dr. Standley completed her postdoctoral training at Princeton University, and received her PhD in Genetics, with an emphasis on biomedical parasitology, from the University of Nottingham (joint program with the Natural History Museum, London). She received her MSc and BA degrees from the University of Oxford and the University of Cambridge, respectively. </p> ',
  },
  {
    name: 'Dr. Claude Millogo, MD',
    subtitle: 'CDC/IANPHI In-Country Consultant, Burkina Faso',
    photo: 'Millogo.jpg',
    bio:
      '<p>Dr. Claude Millogo has been with IANPHI since June 2018, working with the Ministry of Health Burkina Faso, U.S. CDC and other partners to stand up the newly established National Public Health institute. She also served as EOC specialist, working with Voluntary Oversees Service, the Ministry of Health of Burkina Faso and Global Polio Eradication Initiative (GPEI) partners to strengthen the Polio Emergency Operations Center. Dr. Millogo has worked for over 20 years for the US Government in Burkina Faso in the field of public health. Prior joining IANPHI, Dr Millogo served as Associate Peace Corps Director for public health. She also worked with UNICEF and USAID as program officer under their Family health and health financing project. <p/><p>Dr Millogo spent over nine years working with the Ministry of Health, Burkina Faso as practitioner.<p/><p>Trained as a physician, she earned her public health diploma from the University of Nancy, France. Dr. Millogo has received a national recognition from the Government of Burkina Faso for her public service toward the wellbeing of women.</p>',
  },
  {
    name: 'Mr. Jim Banaski',
    photo: 'Banaski.jpg',
    bio:
      '<p>Mr. Jim Banaski is a Senior Technical Advisor for Global Health with CRDF Global. Mr. Banaski is a world-wide recognized expert in the field of Public Health Emergency Management and the development of Public Health Preparedness programs. Mr. Banaski retired from the US Centers for Disease Control and Prevention after 28 years of combined federal service, having also served with the Department of Defense, and the US Army. Mr. Banaski has provided technical assistance to countries in Central and South America, the Caribbean, Eastern Europe, Central Asia, the Middle East, and Africa. Mr. Banaski has also provided consulting services to the World Health Organization European Regional Office, the US Centers for Disease Control and Prevention, and numerous other businesses that provide capacity development technical assistance.<p/><p>Mr. Banaski holds a dual Bachelor of Science degree in Environmental Science and Biology from Drury University, and a Master of Science degree in Environmental Management from Webster University. Mr. Banaski also holds the Certified Emergency Manager designation from the International Association of Emergency Managers and the Master Exercise Practitioner certification from the US Department of Homeland Security. Mr. Banaski is the co-author of the textbook, “Essentials of Public Health Preparedness and Emergency Management, Second Edition”, published by Jones and Bartlett Learning in 2019. Mr. Banaski is an Adjunct Instructor for the Department of Microbiology & Immunology in the School of Medicine and a Center Affiliate for the Center for Global Health Science and Security, both at Georgetown University. Mr. Banaski has also served as an Adjunct Professor for Drury University, and an Adjunct Instructor for Emory University’s Rollins School of Public Health, and as a Guest Lecturer for The George Washington University’s Milken Institute School of Public Health.</p>',
  },
  {
    name: 'Nevashan Govender',
    photo: 'Nevashan.jpg',
    bio:
      '<p>Nevashan Govender is currently employed as the Operations Manager at the National Emergency Operations Centre (EOC), housed at the National Institute for Communicable Diseases (NICD). However, Nevashan’s association with the National Health Laboratory Service stretches back 14 years to when he embarked on an MSc in Clinical Microbiology and Infectious Diseases at the Centre for Enteric Diseases. This was followed by an internship at the Centre for Hospital Acquired Infections, Antimicrobial Resistance and Mycoses and then a short stint as the laboratory coordinator at the Molecular Mycobacteriology Research Unit. Embarking on the two-year South African Field Epidemiology Training Programme changed his professional trajectory and following completion of an MPH in Epidemiology and Biostatistics, he was employed by the GERMS surveillance programme as a research manager and would eventually become the first NICD provincial epidemiologist seconded to Gauteng. Since 2016, Nevashan has had the task of trying to establish a fully functioning EOC. Recent career highlights include, deployment to Malawi and Mozambique in response to Cyclone Idai, confirmation and response of the 2017-2018 listeriosis outbreak, the current COVID-19 response, and regional and global recognition as an EOC technical expert.</p>',
  },
  {
    name: 'Peter Ahabwe Babigumira',
    photo: 'Babigumira.jpg',
    bio:
      '<p>Peter Ahabwe Babigumira is a pharmacist with health diplomacy, health system strengthening and public health technical expertise. His research focuses on biosecurity, antimicrobial resistance and emergency preparedness. He works with the Infectious Diseases Institute at the College of Health Sciences, Makerere University. </p><p>He is attached to the Uganda Ministry of Health Public Health Emergency Operations Centre (PHEOC) as a Technical Advisor for Emergency Preparedness and Response. He coordinates the surge team at COVID-19 situation room, a specialized PHEOC for COVID-19. He supports international health regulation implementation, monitoring and evaluation. He actively participated in the organization and conducting of Joint external evaluation, After Action Review and simulation exercises. He supports Risk Assessment, Contingency Planning, Training and coordination. He also actively supports the work of the Incident Commander’s Incident Management Teams for COVID-19 and past Ebola virus disease outbreaks. Recent projects include development and implementation of a public health emergency management training curriculum for district health leadership. This has been adapted and used for orientation of new regional EOC’s and NGO teams. </p><p> Prior to working with the EOC, Peter supported health system strengthening for implementation of the International Health Regulations at national, district and hospital levels.</p><p>Peter received a Bachelor of Pharmacy in 2013 from Mbarara University of Science and Technology.</p>',
  },
  {
    name: 'Shawn C. Baker-Garcia',
    photo: 'Baker-Garcia.png',
    bio:
      '<p>Shawn is a security policy professional who has been working with US government agencies and global counterparts since 2008 to develop and implement security-focused national frameworks and related programming. Shawn has particular expertise supporting chemical, biological, radiological, and nuclear (CBRN) nonproliferation and counter-WMD (C-WMD) efforts. Her company, Coalescion, is currently supporting U.S. Department of State grants to do security assistance work in Iraq, Jordan, Cambodia, Laos, Thailand, and Vietnam and under her leadership has assembled a world class executive Board of Directors, International Advisory Board, and volunteer staff that provide on-ramps for new and emerging practitioners in national and international security to optimize global security outcomes by evolving and deploying international engagement strategies and practices. In addition to her role as CEO, Shawn serves as a key “Capacity Capture” subject matter expert (SME) for Coalescion projects to ensure capacity building outcomes are transferrable, integrable, and sustainable for partners around the world. </p><p> Prior to founding Coalescion, Shawn co-founded and served as CEO for two years at a small woman owned business, The Critical Mass, where she focused on sustainability in security assistance programming, through work spanning the Middle East, Europe, and Latin America. She also previously served with the U.S. Department of Energy’s Oak Ridge National Laboratory (ORNL) and as the Baghdad field coordinator in support of the U.S. Department of State, Office of Cooperative Threat Reduction’s (CTR) Biosecurity and Chemical Security Engagement Programs. She holds a Master’s degree in Security Policy Studies from George Washington University’s Elliott School of International Affairs, a Bachelor’s degree in History from the University of California, Santa Cruz, and a certificate of completion from Middlebury College’s Arabic language program.</p>',
  },
]

export default trainerBios
